version: '3'

services:
  ads-postgres-compose:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "Postgres2021!"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./var:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  ads-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "infra@ads.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    ports:
      - "16543:80"
    depends_on:
      - ads-postgres-compose
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge
